import Logo from './logo.svg';
import Capa from './capa.jpg';
import LogoAzul from './logo-azul.svg';
import LogoRosa from './logo-rosa.svg';
import Conexoes from './conexoes.png';
import Aspas from './aspas.svg';
import Card1 from './Card1.png';
import Card2 from './Card2.png';
import Card3 from './Card3.png';
import Card4 from './Card4.png';
import Card5 from './Card5.png';
import Card6 from './Card6.png';
import Card7 from './Card7.png';
import Card8 from './Card8.png';
import Card9 from './Card9.png';
import Card10 from './Card10.png';
import Card11 from './Card11.png';
import Card12 from './Card12.png';

export { Logo, Capa, LogoAzul, LogoRosa, Conexoes, Aspas, Card1, Card2, Card3, Card4, Card5, Card6, Card7, Card8, Card9, Card10, Card11, Card12 };